- name: Build and Push Flask Docker Image
  hosts: master
  become: yes
  tasks:
    - name: Build Docker image
      shell: docker build -t dockerhub_ID/flask-app:latest ../app

    - name: Login to DockerHub
      shell: echo "dockerhub_password" | docker login -u dockerhub_ID --password-stdin

    - name: Push Docker image
      shell: docker push dockerhub_ID/flask-app:latest

